Repository sonata-project/ecommerce, pull requests merged in 2018-02, with the labels that each got.

#516 Updated XML definition for sonata.basket service factory
  src/BasketBundle/Resources/config/basket.xml
Labels: patch

#517 Fixed dependency on SecurityContextInterface
  UPGRADE-3.0.md
  src/OrderBundle/Block/RecentOrdersBlockService.php
  src/OrderBundle/Resources/config/block.xml
Labels: major

#521 Add compatibility with FOSRest 2.0
  src/BasketBundle/Controller/Api/BasketController.php
  src/CustomerBundle/Controller/Api/AddressController.php
  src/CustomerBundle/Controller/Api/CustomerController.php
  src/InvoiceBundle/Controller/Api/InvoiceController.php
  src/OrderBundle/Controller/Api/OrderController.php
  src/ProductBundle/Controller/Api/ProductController.php
  tests/BasketBundle/Controller/Api/BasketControllerTest.php
  tests/CustomerBundle/Controller/Api/AddressControllerTest.php
  tests/CustomerBundle/Controller/Api/CustomerControllerTest.php
  tests/InvoiceBundle/Controller/Api/InvoiceControllerTest.php
  tests/OrderBundle/Controller/Api/OrderControllerTest.php
  tests/ProductBundle/Controller/Api/ProductControllerTest.php
Labels: patch

#519 Dropped compatibility with FOS Rest 1.x
  composer.json
  src/BasketBundle/Controller/Api/BasketController.php
  src/CustomerBundle/Controller/Api/AddressController.php
  src/CustomerBundle/Controller/Api/CustomerController.php
  src/InvoiceBundle/Controller/Api/InvoiceController.php
  src/OrderBundle/Controller/Api/OrderController.php
  src/ProductBundle/Controller/Api/ProductController.php
  tests/BasketBundle/Controller/Api/BasketControllerTest.php
  tests/CustomerBundle/Controller/Api/AddressControllerTest.php
  tests/CustomerBundle/Controller/Api/CustomerControllerTest.php
  tests/InvoiceBundle/Controller/Api/InvoiceControllerTest.php
  tests/OrderBundle/Controller/Api/OrderControllerTest.php
  tests/ProductBundle/Controller/Api/ProductControllerTest.php
Labels: major

#523 Composer improvements
  composer.json
  src/BasketBundle/Controller/BasketController.php
Labels: minor

#526 Removed unnecessary conflict requirement on composer
  composer.json
Labels: pedantic

#527 Simplify FOSRest configuration
  src/BasketBundle/Controller/Api/BasketController.php
  src/CustomerBundle/Controller/Api/AddressController.php
  src/CustomerBundle/Controller/Api/CustomerController.php
  src/ProductBundle/Controller/Api/ProductController.php
  tests/CustomerBundle/Controller/Api/CustomerControllerTest.php
Labels: patch
